### PR TITLE
integrationtests don't work

### PR DESCRIPTION
**Pull request by commuterjoy**
Disabled until someone wants to fix it

### CODE REVIEW

**Comment by commuterjoy** [comment]
not worked for 6 months

https://circleci.com/gh/ftlabs/screens/tree/master

**Comment by commuterjoy** [comment]
Yup, will tidy it up at some point. This is just a quick fix to bump the node version.

Not sure I have admin to merge.

**Comment by seanmtracey** [comment]
Yeah, the tests fell by the wayside after Labs stopped actively developing the project. The tests stopped being in line with the codebase a short time afterwards.

**Comment by seanmtracey** [comment]
The software can be viewed on http://ftlabs-screens-test.herokuapp.com/ if you want to check it works before promoting it to prod.

**Pull request merged**
