### PR TITLE
Have transform reject when a page takes too long to respond

### PR DESCRIPTION
**Pull request by JakeChampion**
This needs tests, please do not merge it just yet.

### CODE REVIEW

**Comment by JakeChampion** [comment]
Arises from https://github.com/ftlabs/screens/issues/57

**Comment by seanmtracey** [comment]
This looks good to me.

**Comment by AdaRoseCannon** [comment]
LGTM :+1: do we cache the failure so it doesn't take 1.5s each time the page loads?

**Comment by railsagainstignorance** [comment]
I tried it (eventually) and it works on my local machine.

@AdaRoseEdwards it does cache the failure.

**Pull request merged**
