### PR TITLE
Upgrade node to 5.6.0

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
https://github.com/Financial-Times/ft-labs/issues/2

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
Wut... the failing test succeeded then failed restoring the default url for the next test.

One test failed locally too, same test. But passed on a different branch. Will investigate after doing 5.6.0 to to other repos.

Probably safe to merge though. But maybe best not to until tests pass.

**Comment by JakeChampion** [comment]
@AdaRoseEdwards Any update on this?

**Comment by AdaRoseCannon** [comment]
Sorry not yet I've been engaged dealing with something else. I'll have another look at the tests find what it is failing.

**Comment by AdaRoseCannon** [comment]
I've taken a look into the tests and they seem to fail infrequently and irregularly on my local machine making debugging nigh impossible :(

The failing tests on circleci also seem to be infrequent.

**Comment by AdaRoseCannon** [comment]
Rebuilt now works :(

**Pull request merged**
